spring.application.name=EloProject
spring.mongodb.host=${DB_HOST}
spring.mongodb.port=${DB_PORT}
spring.mongodb.database=${DB_NAME}
spring.mongodb.auto-index-creation=true
spring.graphql.graphiql.enabled=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG